version: "3.8"

services:
  # web:
  #   build: .
  #   command: python3 manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/school
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - .env

  #   depends_on:
  #     - srv-postgres

  srv-postgres:
    container_name: school_postgres
    image: postgres:16.0-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # srv-redis:
  #   container_name: school_redis
  #   image: redis:alpine
  #   hostname: school_redis
  #   env_file:
  #     - .env
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   volumes:
  #     - redis_data:/data

  # srv-nginx:
  #   image: nginx:latest
  #   container_name: school_nginx
  #   hostname: school_nginx
  #   ports:
  #     - 7777:80
  #   volumes:
  #     - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx_conf/conf.d/:/etc/nginx/conf.d
  #     - ./ui:/usr/share/nginx/html

volumes:
  postgres_data:
